title: Las alergias y su diagn&oacute;stico&#58; un di&aacute;logo con la comunidad
description: Estrategia de apropiaci&oacute;n social

theme: jekyll-theme-minimal

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opi-lab.github.io/alergias-asc/" # the base hostname & protocol for your site

logo: images/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
