theme: jekyll-theme-minimal

title: Las alergias y su diagnóstico: un diálogo con la comunidad
description: Estrategia de apropiación social

logo: images/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
