theme: jekyll-theme-minimal

title: Las alergias y su diagn&oacute;stico: un di&aacute;logo con la comunidad
description: Estrategia de apropiaci&oacute;n social

logo: images/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
